#!/usr/bin/env python3
"""
Cayenne Login Credentials
"""

__author__ = "Nick Schiffer"
__version__ = "1.0.0"


MQTT_USERNAME = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
MQTT_PASSWORD = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
MQTT_PORT = 8883

CLIENT_ID_LIST = [
    "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
]
